[package]
name = "argent"
version = "0.1.0"
authors = ["Olivier Sarrouy <osarrouy@protonmail.com>"]
edition = "2018"

[dependencies]
web3 = "0.9.0"
clap = "2.33.0"
colored = "1.9"
lazy_static = "1.4.0"
ethereum-types = "0.8.0"
tiny-keccak = "1.4.2"
dialoguer = "0.5.0"